name: Deploy Ngx Auth Service

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Copy to Droplet
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "."
          target: "/opt/ngx-nestjs-services/ngx-auth-service"

      - name: SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /opt/ngx-nestjs-services/ngx-auth-service
            echo "🔑 Writing .env from GitHub secrets..."
            echo "PORT=${{ secrets.PORT }}" > .env
            echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
            echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> .env
            echo "JWT_ISSUER=${{ secrets.JWT_ISSUER }}" >> .env
            echo "JWT_AUDIENCE=${{ secrets.JWT_AUDIENCE }}" >> .env
            echo "JWT_ACCESS_TOKEN_TTL=${{ secrets.JWT_ACCESS_TOKEN_TTL }}" >> .env
            echo "JWT_REFRESH_TOKEN_TTL=${{ secrets.JWT_REFRESH_TOKEN_TTL }}" >> .env
            echo "🚀 Building and starting container..."
            docker build -t ngx-auth-service .
            docker stop ngx-auth-service || true && docker rm ngx-auth-service || true
            docker run -d --name ngx-auth-service --env-file .env -p 3000:3000 ngx-auth-service